#!/bin/bash

set -e

# http://wiki.panotools.org/Panorama_scripting_in_a_nutshell

tools=/Applications/Hugin/HuginTools

path=$1
shift
name=$1
shift
proj="$path/$name.pto"

rm -f "$proj"

$tools/pto_gen -p 1 -o "$proj" "$1"
shift

while [ -n "$1" ]; do
  img="$1"
  tmp=`mktemp -t pano`
  $tools/pto_gen -p 1 -o "$tmp" "$img"
  $tools/pto_merge -o "$proj" "$proj" "$tmp"
  rm "$tmp"
  shift
done

perl -p -i -e 's/hugin_outputImageType tif/hugin_outputImageType jpg/' "$proj"
perl -p -i -e 's/hugin_outputJPEGQuality 100/hugin_outputJPEGQuality 80/' "$proj"
# perl -p -i -e 's/hugin_outputImageTypeCompression LZW/hugin_outputImageTypeCompression DEFLATE/' "$proj"

