#!/bin/bash

set -e

# http://wiki.panotools.org/Panorama_scripting_in_a_nutshell

tools=/Applications/Hugin/HuginTools

path=$1
shift
name=$1
shift
proj="$path/$name.pto"

rm -f /tmp/apa
echo "proj $proj" >> /tmp/apa

rm -f "$proj"

echo $tools/pto_gen -p 1 -o "$proj" "$1" >> /tmp/apa
$tools/pto_gen -p 1 -o "$proj" "$1" 2>>/tmp/apa
echo "img1 $1" >> /tmp/apa
shift

while [ -n "$1" ]; do
  img="$1"
  echo "img $img" >> /tmp/apa
  tmp=`mktemp -t pano`
  $tools/pto_gen -p 1 -o "$tmp" "$img"
  $tools/pto_merge -o "$proj" "$proj" "$tmp"
  rm "$tmp"
  shift
done

