#!/bin/bash

set -e

# http://wiki.panotools.org/Panorama_scripting_in_a_nutshell

tools=/Applications/Hugin/HuginTools

path=$1
name=$2
temp=$3
proj=$path/$name.pto

work="$temp"
mkdir -p "$work"

cd "$work"

echo $name
echo $proj
$tools/pto2mk -o "$name.mk" -p "$name" "$proj"
export PATH="$PATH:$tools"
make -f "$name.mk" all
make -f "$name.mk" clean

mv "$work/$name.tif" "$path/$name.tif"

